name: Pull Requests Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest gspread
          if [ -f requirements.txt]; then pip install -r requirements.txt; fi

      - name: Create superuser_secret.json
        run: ./.github/scripts/superuser_file_creation.sh
        env:
          SUPERUSER_SECRET: ${{ secrets.SUPERUSER_SECRET }}

      - name: Lint with flake8
        run: |
          # Stop the build if there are any Python syntax errors or undefined names.
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

      - name: Test with pytest
        run: pytest -v

  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Generate coverage report
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
